[project]
name = "phreeq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13, <3.14"
dependencies = [
    "pandas>=2.3.3",
    "phreeqpy>=0.6.0",
    "jinja2",
    "fastapi",
    "shiny",
    "plotly",
    "shinywidgets"
]
